# Generated by Django 2.2.4 on 2019-08-29 10:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('wx', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
